on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    
name: create-pull-request if newer nbminer available
jobs:

  checkNewerAndPullRequest:
    runs-on: ubuntu-latest

    steps:

      # checkout 
      - uses: actions/checkout@v2

      # compare versions
      - name: Get latest nbminer release version
        id: version
        run: |
          echo "::set-output name=NBMINER_VERSION::$(curl -s https://github.com/NebuTech/NBMiner/releases.atom | grep -m1 -oP '(?<=135897748\/v).*?(?=\<\/id\>)')"

      - name: Replace version in Dockerfile with latest
        run: sed -i '/ENV NBMINER_VERSION/c\ENV NBMINER_VERSION="${{ steps.version.outputs.NBMINER_VERSION }}"' Dockerfile

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update nbminer ${{ steps.version.outputs.NBMINER_VERSION }}
          title: update nbminer to ${{ steps.version.outputs.NBMINER_VERSION }}
          body: This PR is auto-generated by pr-if-newer-upstream workflow.
          # labels: automated pr
          branch: nbminer-v${{ steps.version.outputs.NBMINER_VERSION }}