on:
  push:
    branches: [main]

name: Build Docker image and push to repositories
jobs:

  build-and-push:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # grab nbminer version number
      - name: Get nbminer version from Dockerfile
        id: version
        run: |
          echo "::set-output name=NBMINER_VERSION::$(cat Dockerfile | grep -m1 -oP '(?<=NBMINER_VERSION=\").*?(?=\")')"

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            devenvy/nbminer:latest
            devenvy/nbminer:v${{ steps.version.outputs.NBMINER_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}